from flask import Flask, jsonify, render_template
import json
import os

app = Flask(__name__)

# API routes (for machines/frontend)

@app.route('/api/datos')
def obtener_datos():
    #Reads the JSON generated by main.py and exposes it as a REST API.
    if not os.path.exists('reporte.json'):
        # If the user has not run main.py, we return an HTTP 404 error.
        return jsonify({"error": "The file reporte.json does not exist. Run main.py first."}), 404

    with open('reporte.json', 'r', encoding='utf-8') as f:
        datos = json.load(f)

    return jsonify(datos)

# Web interface routes (for humans)

@app.route('/')
def index():
    #Home page. Renders the HTML Dashboard.
    # render_template automatically searches inside the 'templates/' folder
    return render_template('index.html')


if __name__ == '__main__':
    # We start the server in debug mode (it restarts itself if you change the code)
    # Listen on port 5000
    print("Starting Backend server...")
    app.run(debug=True, host='0.0.0.0', port=5000)
